"""This file was generated by xsdata, v24.3.1, on 2024-04-01 01:17:39

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from nfelib_client.nfe.soap.nferetautorizacao4 import (
    NfeDadosMsg,
    NfeResultMsg,
    NfeRetAutorizacao4SoapNfeRetAutorizacaoLote,
    NfeRetAutorizacao4SoapNfeRetAutorizacaoLoteInput,
    NfeRetAutorizacao4SoapNfeRetAutorizacaoLoteOutput,
)

__all__ = [
    "NfeRetAutorizacao4SoapNfeRetAutorizacaoLote",
    "NfeRetAutorizacao4SoapNfeRetAutorizacaoLoteInput",
    "NfeRetAutorizacao4SoapNfeRetAutorizacaoLoteOutput",
    "NfeDadosMsg",
    "NfeResultMsg",
]
